import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useQuery } from 'urql';
import TaskList from '../components/task-list';
import Header from '../components/header';
import CreateTaskDialog from '../components/create-task-dialog';
import { StackDivider, useDisclosure, VStack } from '@chakra-ui/react';
import UserTags from '../components/user-tags';
import { useState } from 'react';

const QueryUsersTasks = `
query {
  users {
    id
    name
    email
  }
  tasks {
    id
    title
    authorId
    author {
      name, email, id
    }
    completed
  }
}`;


const Home: NextPage = () => {
  const [result, reexecuteQuery] = useQuery({
    query: QueryUsersTasks,
    requestPolicy: "cache-first"
  });
  const { data, fetching, error } = result;
  const { isOpen, onOpen, onClose } = useDisclosure();
  const [selectedUsers, setSelectedUsers] = useState<number[]>(data && data.users ? data.users.map((user: any) => user.id) : [])

  if (fetching) return <p>Loading...</p>;
  if (error) return <p>Oh no... {error.message}</p>;

  function onChangeUserTags(userId: number) {
    let newSelectedUsers = [...selectedUsers];
    if (selectedUsers.includes(userId)) {
      newSelectedUsers.splice(selectedUsers.indexOf(userId), 1);
    } else {
      newSelectedUsers.push(userId);
    }
    setSelectedUsers(newSelectedUsers);
  }

  console.log("index")

  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js + GraphQL Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <VStack spacing={4} divider={<StackDivider borderColor='gray.200' />}>
          <UserTags users={data.users} changeTags={onChangeUserTags} selectedTags={selectedUsers} />
          <TaskList data={data} title="Todo" completed={false} color="rgb(250,120,120)" openCreateTaskDialog={onOpen} selectedUsers={selectedUsers} />
          <TaskList data={data} title="Completed" completed={true} color="rgb(120,250,120)" selectedUsers={selectedUsers} />
        </VStack>
      </main>

      <CreateTaskDialog open={isOpen} onClose={onClose} users={data.users} />

    </div >
  )
}

export default Home
