import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useQuery } from 'urql';
import TaskList from '../components/task-list';
import Header from '../components/header';
import CreateTaskDialog from '../components/create-task-dialog';
import { useState } from 'react';

const TasksQuery = `
  query {
    tasks {
      id
      title
      authorId
      completed
    }
  }
`;
// const UsersQuery = `
//   query {
//     users {
//       id
//       email
//       name
//     }
//   }
// `;
const Home: NextPage = () => {
  const [result, reexecuteQuery] = useQuery({
    query: TasksQuery,
  });
  const { data, fetching, error } = result;

  const [dialogOpen, setDialogOpen] = useState(false);

  if (fetching) return <p>Loading...</p>;
  if (error) return <p>Oh no... {error.message}</p>;



  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js + GraphQL Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <button onClick={() => {
          setDialogOpen(!dialogOpen)
        }}>Create new</button>
        <TaskList data={data} title="Todo" completed={false} color="rgb(250,120,120)" />
        <TaskList data={data} title="Completed" completed={true} color="rgb(120,250,120)" />
        <CreateTaskDialog open={dialogOpen} />
      </main>



    </div>
  )
}

export default Home
